"""empty message

Revision ID: 28b0d6366930
Revises: 5b0f6f8bb9e8
Create Date: 2020-09-09 09:48:59.026037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28b0d6366930'
down_revision = '5b0f6f8bb9e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
