"""empty message

Revision ID: 4158eb466d91
Revises: 7be9725ca59d
Create Date: 2020-09-09 10:03:33.070726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4158eb466d91'
down_revision = '7be9725ca59d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
