"""empty message

Revision ID: 6761b597f65b
Revises: 4158eb466d91
Create Date: 2020-09-09 14:42:52.281011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6761b597f65b'
down_revision = '4158eb466d91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
