"""empty message

Revision ID: 783a4b75539d
Revises: 8e9a1fd625aa
Create Date: 2020-09-12 15:39:01.370992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '783a4b75539d'
down_revision = '8e9a1fd625aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
