"""empty message

Revision ID: 7be9725ca59d
Revises: d77fcfb01124
Create Date: 2020-09-09 10:00:08.837457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7be9725ca59d'
down_revision = 'd77fcfb01124'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
