"""empty message

Revision ID: 7ef9136e2988
Revises: 28b0d6366930
Create Date: 2020-09-09 09:54:42.715913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ef9136e2988'
down_revision = '28b0d6366930'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
