"""empty message

Revision ID: 8e9a1fd625aa
Revises: 917c568d1df5
Create Date: 2020-09-12 12:58:38.753660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e9a1fd625aa'
down_revision = '917c568d1df5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('contact', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'contacts', ['contact'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'contact')
    # ### end Alembic commands ###
