"""empty message

Revision ID: 917c568d1df5
Revises: f59e0444726b
Create Date: 2020-09-11 15:25:44.983671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '917c568d1df5'
down_revision = 'f59e0444726b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_contact_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'contact')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('contact', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_contact_fkey', 'users', 'contacts', ['contact'], ['id'])
    # ### end Alembic commands ###
