"""empty message

Revision ID: 957a055d5d90
Revises: f2f2e5a3c0da
Create Date: 2020-09-09 15:12:49.351797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '957a055d5d90'
down_revision = 'f2f2e5a3c0da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
