"""empty message

Revision ID: bc02e542b07f
Revises: 783a4b75539d
Create Date: 2020-09-12 15:39:19.480788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc02e542b07f'
down_revision = '783a4b75539d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
