"""empty message

Revision ID: d77fcfb01124
Revises: 7ef9136e2988
Create Date: 2020-09-09 09:56:54.420291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd77fcfb01124'
down_revision = '7ef9136e2988'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
