"""empty message

Revision ID: f59e0444726b
Revises: 957a055d5d90
Create Date: 2020-09-09 15:27:59.558302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f59e0444726b'
down_revision = '957a055d5d90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
